"""Research memo builder: assembles forensic score results into a Markdown report."""

from datetime import date
from typing import Optional

from src.metrics.altman import AltmanResult
from src.metrics.beneish import BeneishResult
from src.metrics.piotroski import PiotroskiResult
from src.metrics.sloan import SloanResult


def build_memo(
    ticker: str,
    beneish: Optional[BeneishResult],
    altman: Optional[AltmanResult],
    sloan: Optional[SloanResult],
    piotroski: Optional[PiotroskiResult],
    agent_summary: str = "",
    data_sources: Optional[list[str]] = None,
    uncertainty_notes: Optional[list[str]] = None,
) -> str:
    """
    Build a Markdown research memo from forensic score results.

    The memo is structured so raw data, computed metrics, and AI interpretation
    are clearly separated. The agent_summary section is the only LLM-generated content.
    """
    today = date.today().isoformat()
    lines = [
        f"# Research Memo: {ticker}",
        f"Date: {today}",
        "",
        "---",
        "",
        "## Risk Summary",
        "",
    ]

    if beneish:
        flag_emoji = {"MANIPULATION_RISK": "CAUTION", "BORDERLINE": "WATCH", "CLEAN": "OK"}.get(beneish.flag, "")
        lines.append(f"| Beneish M-Score | {beneish.m_score:.4f} | {flag_emoji} — {beneish.flag} |")

    if altman:
        flag_emoji = {"SAFE": "OK", "GREY": "WATCH", "DISTRESS": "CAUTION"}.get(altman.zone, "")
        lines.append(f"| Altman Z-Score | {altman.z_score:.4f} | {flag_emoji} — {altman.zone} ZONE |")

    if sloan:
        flag_emoji = {"ELEVATED": "CAUTION", "MODERATE": "WATCH", "CLEAN": "OK"}.get(sloan.flag, "")
        lines.append(f"| Sloan Accruals Ratio | {sloan.accruals_ratio * 100:.2f}% | {flag_emoji} — {sloan.flag} |")

    if piotroski:
        flag_emoji = {"STRONG": "OK", "NEUTRAL": "WATCH", "WEAK": "CAUTION"}.get(piotroski.flag, "")
        lines.append(f"| Piotroski F-Score | {piotroski.f_score}/9 | {flag_emoji} — {piotroski.flag} |")

    lines.extend(["", "---", ""])

    # Red flags
    red_flags = _collect_red_flags(beneish, altman, sloan, piotroski)
    if red_flags:
        lines.append("## Red Flags")
        lines.append("")
        for flag in red_flags:
            lines.append(f"- {flag}")
        lines.append("")

    # Green flags
    green_flags = _collect_green_flags(beneish, altman, sloan, piotroski)
    if green_flags:
        lines.append("## Green Flags")
        lines.append("")
        for flag in green_flags:
            lines.append(f"- {flag}")
        lines.append("")

    lines.extend(["---", ""])

    # Score detail
    lines.append("## Score Detail")
    lines.append("")
    if beneish:
        lines.append("### Beneish M-Score")
        lines.append("```")
        lines.append(beneish.summary())
        lines.append("```")
        lines.append("")
    if altman:
        lines.append("### Altman Z-Score")
        lines.append("```")
        lines.append(altman.summary())
        lines.append("```")
        lines.append("")
    if sloan:
        lines.append("### Sloan Accruals Ratio")
        lines.append("```")
        lines.append(sloan.summary())
        lines.append("```")
        lines.append("")
    if piotroski:
        lines.append("### Piotroski F-Score")
        lines.append("```")
        lines.append(piotroski.summary())
        lines.append("```")
        lines.append("")

    lines.extend(["---", ""])

    # AI interpretation (clearly labeled)
    if agent_summary:
        lines.append("## Agent Interpretation")
        lines.append("")
        lines.append("> The following section is generated by an AI model.")
        lines.append("> All numbers above this line are deterministic and source-linked.")
        lines.append("> The interpretation below should not be treated as investment advice.")
        lines.append("")
        lines.append(agent_summary)
        lines.append("")
        lines.extend(["---", ""])

    # Data sources
    if data_sources:
        lines.append("## Data Sources")
        lines.append("")
        for source in data_sources:
            lines.append(f"- {source}")
        lines.append("")

    # Uncertainty notes
    if uncertainty_notes:
        lines.append("## Uncertainty Notes")
        lines.append("")
        for note in uncertainty_notes:
            lines.append(f"- {note}")
        lines.append("")

    lines.extend([
        "---",
        "",
        "_For research and educational purposes only. Not investment advice._",
        "_Forensic scores are probability indicators, not proof of fraud or financial distress._",
    ])

    return "\n".join(lines)


def _collect_red_flags(
    beneish: Optional[BeneishResult],
    altman: Optional[AltmanResult],
    sloan: Optional[SloanResult],
    piotroski: Optional[PiotroskiResult],
) -> list[str]:
    flags = []
    if beneish and beneish.flag == "MANIPULATION_RISK":
        flags.append(f"M-Score {beneish.m_score:.2f} exceeds -2.22 threshold — review receivables and gross margin trends")
    if beneish and beneish.flag == "BORDERLINE":
        flags.append(f"M-Score {beneish.m_score:.2f} is in borderline range (-2.49 to -2.22)")
    if altman and altman.zone == "DISTRESS":
        flags.append(f"Altman Z-Score {altman.z_score:.2f} is in distress zone (< 1.81) — elevated bankruptcy risk")
    if altman and altman.zone == "GREY":
        flags.append(f"Altman Z-Score {altman.z_score:.2f} is in grey zone (1.81–2.99) — uncertainty about solvency")
    if sloan and sloan.flag == "ELEVATED":
        flags.append(f"Sloan accruals ratio {sloan.accruals_ratio * 100:.1f}% above 5% — earnings quality concern, cash conversion below reported income")
    if sloan and sloan.flag == "MODERATE":
        flags.append(f"Sloan accruals ratio {sloan.accruals_ratio * 100:.1f}% above 2% — monitor earnings quality")
    if piotroski and piotroski.flag == "WEAK":
        flags.append(f"Piotroski F-Score {piotroski.f_score}/9 indicates weak fundamentals across multiple criteria")
    return flags


def _collect_green_flags(
    beneish: Optional[BeneishResult],
    altman: Optional[AltmanResult],
    sloan: Optional[SloanResult],
    piotroski: Optional[PiotroskiResult],
) -> list[str]:
    flags = []
    if beneish and beneish.flag == "CLEAN":
        flags.append(f"M-Score {beneish.m_score:.2f} is below -2.49 — no earnings manipulation signal")
    if altman and altman.zone == "SAFE":
        flags.append(f"Altman Z-Score {altman.z_score:.2f} is in safe zone (> 2.99) — low near-term bankruptcy risk")
    if sloan and sloan.flag == "CLEAN":
        flags.append(f"Sloan accruals ratio {sloan.accruals_ratio * 100:.1f}% is below 2% — earnings quality appears sound")
    if piotroski and piotroski.flag == "STRONG":
        flags.append(f"Piotroski F-Score {piotroski.f_score}/9 indicates strong fundamentals across most criteria")
    return flags
